version: '3'
services:
  strapi:
    image: strapi/strapi:alpine
    restart: always
    environment:
      DATABASE_CLIENT: "${DATABASE_CLIENT}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - ./strapi:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./postgres:/var/lib/postgresql/data
